name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  tf-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v3

      - name: Cache Terraform state
        uses: actions/cache@v3
        with:
          path: |
            .terraform
            terraform.tfstate
            terraform.tfstate.backup
          key: terraform-state-${{ github.ref }}-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            terraform-state-${{ github.ref }}-

      - uses: hashicorp/setup-terraform@v3

      - name: Verify Terraform version
        run: terraform --version

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform destroy
        run: terraform destroy -auto-approve
      
      - name: Remove cached Terraform state files
        run: |
          rm -rf .terraform
          rm -f terraform.tfstate
          rm -f terraform.tfstate.backup
          rm -f terraform-state-refs*
